nama = input("Nama : ")
nim = int(input("NIM : "))
kelasParalel = int(input("Kelas Paralel: "))
ttl = input("Tempat/Tanggal Lahir : ")
alamat = input("Alamat : ")
hobby = input("Hobby : ")
noHP = int(input("No. Hp : "))

print("\nOUTPUT\n")
print(f"Nama : {nama}")
print(f"NIM : {nim}")
print(f"Kelas Paralel : {kelasParalel}")
print(f"Tempat/Tanggal Lahir : {ttl}")
print(f"Alamat : {alamat}")
print(f"Hobby : {hobby}")
print(f"No. Hp : {noHP}")
