print("###########################")
print("#                         #")
print("#    Muhammad Fadillah    #")
print("#      2410817210001      #")
print("#                         #")
print("###########################")